import type { Metadata } from "next"
import { Inter, Nunito } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={nunito.className}>{children}</body>
    </html>
  )
}
